"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const controllers_1 = require("../controllers");
const router = (0, express_1.Router)();
router.get("/users/:id", controllers_1.users_controller.getOneUser);
router.get("/users", controllers_1.users_controller.getAllUser);
router.delete("/users/:id", controllers_1.users_controller.deleteUser);
router.get("/profiles/:id", controllers_1.profiles_controller.getOneProfile);
router.get("/profiles", controllers_1.profiles_controller.getAllProfile);
router.put("/profiles/:id", controllers_1.profiles_controller.putProfile);
router.get("/posts/:id", controllers_1.posts_controller.getOnePost);
router.get("/posts", controllers_1.posts_controller.getAllPost);
router.post("/posts", controllers_1.posts_controller.postPost);
router.put("/posts/:id", controllers_1.posts_controller.putPost);
router.delete("/posts/:id", controllers_1.posts_controller.deletePost);
exports.default = router;
